<table class="table table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>Comment</th>
			<th>By</th>
			<th>Date</th>
			<th>Staus</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1</td>
			<td>comment</td>
			<td>ram</td>
			<td>date</td>
			<td>active</td>
		</tr>
	</tbody>
</table>